version: '3'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: capdenise
      WORDPRESS_DB_PASSWORD: spiders4lyfe
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    depends_on:
      - db
    restart: always

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: capdenise
      MYSQL_PASSWORD: spiders4lyfe
      MYSQL_ROOT_PASSWORD: spiders4lyfe
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data: 